# Generated by Django 5.1.1 on 2024-11-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
